# Cada copy desses leva desde <1s até 1 min (em uma máquina comum, não rodei em um servidor ou em SSD)
# Os arquivos estão em ordem de tamanho
# Preste atenção se a sua conexão tem timeout

\copy siconv.empenho_desembolso ("id_desembolso", "id_empenho", "valor_grup")o FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_empenho_desembolso.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.ingresso_contrapartida ("nr_convenio", "dt_ingresso_contrapartida", "vl_ingresso_contrapartida") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_ingresso_contrapartida.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.prorroga_oficio ("nr_convenio", "nr_prorroga", "dt_inicio_prorroga", "dt_fim_prorroga", "dias_prorroga", "dt_assinatura_prorroga", "sit_prorroga") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_prorroga_oficio.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.proponentes ("identif_proponente", "nm_proponente", "municipio_proponente", "uf_proponente", "endereco_proponente", "bairro_proponente", "cep_proponente", "email_proponente", "telefone_proponente", "fax_proponente") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_proponentes.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.programa_proposta ("id_programa", "id_proposta") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_programa_proposta.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.desbloqueio ("nr_convenio", "nr_ob", "data_cadastro", "data_envio", "tipo_recurso_desbloqueio", "vl_total_desbloqueio", "vl_desbloqueado", "vl_bloqueado") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_desbloqueio_cr.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.consorcios ("id_proposta", "cnpj_consorcio", "nome_consorcio", "codigo_cnae_primario", "desc_cnae_primario", "codigo_cnae_secundario", "desc_cnae_secundario", "cnpj_participante", "nome_participante") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_consorcios.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.desembolso ("id_desembolso", "nr_convenio", "dt_ult_desembolso", "qtd_dias_sem_desembolso", "data_desembolso", "ano_desembolso", "mes_desembolso", "nr_siafi", "vl_desembolsado") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_desembolso.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.emenda ("id_proposta", "qualif_proponente", "cod_programa_emenda", "nr_emenda", "nome_parlamentar", "beneficiario_emenda", "ind_impositivo", "tipo_parlamentar", "valor_repasse_proposta_emenda", "valor_repasse_emenda") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_emenda.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.empenho ("id_empenho", "nr_convenio", "nr_empenho", "tipo_nota", "desc_tipo_nota", "data_emissao", "cod_situacao_empenho", "desc_situacao_empenho", "valor_empenho") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_empenho.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.programa ("cod_orgao_sup_programa", "desc_orgao_sup_programa", "id_programa", "cod_programa", "nome_programa", "sit_programa", "data_disponibilizacao", "ano_disponibilizacao", "dt_prog_ini_receb_prop", "dt_prog_fim_receb_prop", "dt_prog_ini_emenda_par", "dt_prog_fim_emenda_par", "dt_prog_ini_benef_esp", "dt_prog_fim_benef_esp", "modalidade_programa", "natureza_juridica_programa", "uf_programa", "acao_orcamentaria") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_programa.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.convenio ("nr_convenio", "id_proposta", "dia", "mes", "ano", "dia_assin_conv", "sit_convenio", "subsituacao_conv", "situacao_publicacao", "instrumento_ativo", "ind_opera_obtv", "nr_processo", "ug_emitente", "dia_publ_conv", "dia_inic_vigenc_conv", "dia_fim_vigenc_conv", "dia_fim_vigenc_original_conv", "dias_prest_contas", "dia_limite_prest_contas", "situacao_contratacao", "ind_assinado", "motivo_suspensao", "ind_foto", "qtde_convenios", "qtd_ta", "qtd_prorroga", "vl_global_conv", "vl_repasse_conv", "vl_contrapartida_conv", "vl_empenhado_conv", "vl_desembolsado_conv", "vl_saldo_reman_tesouro", "vl_saldo_reman_convenente", "vl_rendimento_aplicacao", "vl_ingresso_contrapartida", "vl_saldo_conta", "vl_global_original_conv") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_convenio.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.meta_crono_fisico ("id_meta", "nr_convenio", "cod_programa", "nome_programa", "nr_meta", "tipo_meta", "desc_meta", "data_inicio_meta", "data_fim_meta", "uf_meta", "municipio_meta", "endereco_meta", "cep_meta", "qtd_meta", "und_fornecimento_meta", "vl_meta") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_meta_crono_fisico.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.termo_aditivo ("nr_convenio", "numero_ta", "tipo_ta", "vl_global_ta", "vl_repasse_ta", "vl_contrapartida_ta", "dt_assinatura_ta", "dt_inicio_ta", "dt_fim_ta", "justificativa_ta") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_termo_aditivo.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.obtv_convenente ("nr_mov_fin", "identif_favorecido_obtv_conv", "nm_favorecido_obtv_conv", "tp_aquisicao", "vl_pago_obtv_conv") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_obtv_convenente.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.etapa_crono_fisico ("id_meta", "id_etapa", "nr_etapa", "desc_etapa", "data_inicio_etapa", "data_fim_etapa", "uf_etapa", "municipio_etapa", "endereco_etapa", "cep_etapa", "qtd_etapa", "und_fornecimento_etapa", "vl_etapa") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_etapa_crono_fisico.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.historico_situacao ("id_proposta", "nr_convenio", "dia_historico_sit", "historico_sit", "dias_historico_sit", "cod_historico_sit") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_historico_situacao.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.pagamento ("nr_mov_fin", "nr_convenio", "identif_fornecedor", "nome_fornecedor", "tp_mov_financeira", "data_pag", "nr_dl", "desc_dl", "vl_pago") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_pagamento.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.proposta ("id_proposta", "uf_proponente", "munic_proponente", "cod_munic_ibge", "cod_orgao_sup", "desc_orgao_sup", "natureza_juridica", "nr_proposta", "dia_prop", "mes_prop", "ano_prop", "dia_proposta", "cod_orgao", "desc_orgao", "modalidade", "identif_proponente", "nm_proponente", "cep_proponente", "endereco_proponente", "bairro_proponente", "nm_banco", "situacao_conta", "situacao_projeto_basico", "sit_proposta", "dia_inic_vigencia_proposta", "dia_fim_vigencia_proposta", "objeto_proposta", "vl_global_prop", "vl_repasse_prop", "vl_contrapartida_prop") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_proposta.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
\copy siconv.plano_aplicacao_detalhado ("id_proposta", "sigla", "municipio", "natureza_aquisicao", "descricao_item", "cep_item", "endereco_item", "tipo_despesa_item", "natureza_despesa", "sit_item", "cod_natureza_despesa", "qtd_item", "valor_unitario_item", "valor_total_item") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_plano_aplicacao_detalhado.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);

--      Resultado na minha máquina usando uma extensão que liga o sublime text com o psql no cmd
--      
--       */
--      -- Executed querie(s) at 2019-06-13 16:53:42 took 587.188 s --
--      --------------------------------------------------------------
--      \copy siconv2.empenho_desembolso ("id_desembolso", "id_empenho", "valor_grupo") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_empenho_desembolso.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.ingresso_contrapartida ("nr_convenio", "dt_ingresso_contrapartida", "vl_ingresso_contrapartida") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_ingresso_contrapartida.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.prorroga_oficio ("nr_convenio", "nr_prorroga", "dt_inicio_prorroga", "dt_fim_prorroga", "dias_prorroga", "dt_assinatura_prorroga", "sit_prorroga") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_prorroga_oficio.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.proponentes ("identif_proponente", "nm_proponente", "municipio_proponente", "uf_proponente", "endereco_proponente", "bairro_proponente", "cep_proponente", "email_proponente", "telefone_proponente", "fax_proponente") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_proponentes.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.programa_proposta ("id_programa", "id_proposta") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_programa_proposta.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.desbloqueio ("nr_convenio", "nr_ob", "data_cadastro", "data_envio", "tipo_recurso_desbloqueio", "vl_total_desbloqueio", "vl_desbloqueado", "vl_bloqueado") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_desbloqueio_cr.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.consorcios ("id_proposta", "cnpj_consorcio", "nome_consorcio", "codigo_cnae_primario", "desc_cnae_primario", "codigo_cnae_secundario", "desc_cnae_secundario", "cnpj_participante", "nome_participante") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_consorcios.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.desembolso ("id_desembolso", "nr_convenio", "dt_ult_desembolso", "qtd_dias_sem_desembolso", "data_desembolso", "ano_desembolso", "mes_desembolso", "nr_siafi", "vl_desembolsado") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_desembolso.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.emenda ("id_proposta", "qualif_proponente", "cod_programa_emenda", "nr_emenda", "nome_parlamentar", "beneficiario_emenda", "ind_impositivo", "tipo_parlamentar", "valor_repasse_proposta_emenda", "valor_repasse_emenda") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_emenda.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.empenho ("id_empenho", "nr_convenio", "nr_empenho", "tipo_nota", "desc_tipo_nota", "data_emissao", "cod_situacao_empenho", "desc_situacao_empenho", "valor_empenho") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_empenho.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.programa ("cod_orgao_sup_programa", "desc_orgao_sup_programa", "id_programa", "cod_programa", "nome_programa", "sit_programa", "data_disponibilizacao", "ano_disponibilizacao", "dt_prog_ini_receb_prop", "dt_prog_fim_receb_prop", "dt_prog_ini_emenda_par", "dt_prog_fim_emenda_par", "dt_prog_ini_benef_esp", "dt_prog_fim_benef_esp", "modalidade_programa", "natureza_juridica_programa", "uf_programa", "acao_orcamentaria") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_programa.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.convenio ("nr_convenio", "id_proposta", "dia", "mes", "ano", "dia_assin_conv", "sit_convenio", "subsituacao_conv", "situacao_publicacao", "instrumento_ativo", "ind_opera_obtv", "nr_processo", "ug_emitente", "dia_publ_conv", "dia_inic_vigenc_conv", "dia_fim_vigenc_conv", "dia_fim_vigenc_original_conv", "dias_prest_contas", "dia_limite_prest_contas", "situacao_contratacao", "ind_assinado", "motivo_suspensao", "ind_foto", "qtde_convenios", "qtd_ta", "qtd_prorroga", "vl_global_conv", "vl_repasse_conv", "vl_contrapartida_conv", "vl_empenhado_conv", "vl_desembolsado_conv", "vl_saldo_reman_tesouro", "vl_saldo_reman_convenente", "vl_rendimento_aplicacao", "vl_ingresso_contrapartida", "vl_saldo_conta", "vl_global_original_conv") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_convenio.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.meta_crono_fisico ("id_meta", "nr_convenio", "cod_programa", "nome_programa", "nr_meta", "tipo_meta", "desc_meta", "data_inicio_meta", "data_fim_meta", "uf_meta", "municipio_meta", "endereco_meta", "cep_meta", "qtd_meta", "und_fornecimento_meta", "vl_meta") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_meta_crono_fisico.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.termo_aditivo ("nr_convenio", "numero_ta", "tipo_ta", "vl_global_ta", "vl_repasse_ta", "vl_contrapartida_ta", "dt_assinatura_ta", "dt_inicio_ta", "dt_fim_ta", "justificativa_ta") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_termo_aditivo.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.obtv_convenente ("nr_mov_fin", "identif_favorecido_obtv_conv", "nm_favorecido_obtv_conv", "tp_aquisicao", "vl_pago_obtv_conv") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_obtv_convenente.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.etapa_crono_fisico ("id_meta", "id_etapa", "nr_etapa", "desc_etapa", "data_inicio_etapa", "data_fim_etapa", "uf_etapa", "municipio_etapa", "endereco_etapa", "cep_etapa", "qtd_etapa", "und_fornecimento_etapa", "vl_etapa") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_etapa_crono_fisico.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.historico_situacao ("id_proposta", "nr_convenio", "dia_historico_sit", "historico_sit", "dias_historico_sit", "cod_historico_sit") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_historico_situacao.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.pagamento ("nr_mov_fin", "nr_convenio", "identif_fornecedor", "nome_fornecedor", "tp_mov_financeira", "data_pag", "nr_dl", "desc_dl", "vl_pago") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_pagamento.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.proposta ("id_proposta", "uf_proponente", "munic_proponente", "cod_munic_ibge", "cod_orgao_sup", "desc_orgao_sup", "natureza_juridica", "nr_proposta", "dia_prop", "mes_prop", "ano_prop", "dia_proposta", "cod_orgao", "desc_orgao", "modalidade", "identif_proponente", "nm_proponente", "cep_proponente", "endereco_proponente", "bairro_proponente", "nm_banco", "situacao_conta", "situacao_projeto_basico", "sit_proposta", "dia_inic_vigencia_proposta", "dia_fim_vigencia_proposta", "objeto_proposta", "vl_global_prop", "vl_repasse_prop", "vl_contrapartida_prop") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_proposta.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      \copy siconv2.plano_aplicacao_detalhado ("id_proposta", "sigla", "municipio", "natureza_aquisicao", "descricao_item", "cep_item", "endereco_item", "tipo_despesa_item", "natureza_despesa", "sit_item", "cod_natureza_despesa", "qtd_item", "valor_unitario_item", "valor_total_item") FROM 'C:/Users/pedro.palotti/Documents/SICONV/DadosSICONV/siconv_plano_aplicacao_detalhado.csv' ( FORMAT('csv'), DELIMITER(';'), QUOTE(E'\"'), HEADER);
--      --------------------------------------------------------------
--      */
--      COPY 212510
--      COPY 181165
--      COPY 79475
--      COPY 49322
--      COPY 805042
--      COPY 177629
--      COPY 53692
--      COPY 256056
--      COPY 157172
--      COPY 274936
--      COPY 92225
--      COPY 171528
--      COPY 249255
--      COPY 258658
--      COPY 1705863
--      COPY 661478
--      COPY 5119763
--      COPY 3642538
--      COPY 803683
--      COPY 3611548
--      